---
- name: Node.js | Package prerequisites for node.js
  action: apt pkg=python-software-properties state=installed update-cache=yes

- name: Node.js | Add the node.js PPA for precise
  action: command add-apt-repository -y ppa:chris-lea/node.js creates=/etc/apt/sources.list.d/chris-lea-node_js-precise.list
  only_if: "'$ansible_distribution_release' == 'precise'"

- name: Node.js | Add the node.js PPA for lucid
  action: command add-apt-repository ppa:chris-lea/node.js
  only_if: "'$ansible_distribution_release' == 'lucid'"
  #when_string: ${ansible_distribution} == 'Ubuntu' and ${ansible_distribution_release} == 'lucid'

- name: Node.js | Install nodejs and npm
  action: apt pkg=nodejs state=installed update-cache=yes
